---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: k8s-scheduler-tester
  name: k8s-scheduler-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-scheduler-tester
  template:
    metadata:
      labels:
        name: k8s-scheduler-tester
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Amsterdam
        - name: OPT_REPLICAS
          value: "3"
        - name: OPT_TIMEOUT
          value: "60"
        - name: OPT_INTERVAL
          value: "30"
        - name: OPT_PROMETHEUS_PORT
          value: "9999"
        - name: OPT_TARGET_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: k8s-scheduler-tester:latest
        imagePullPolicy: Always
        name: k8s-scheduler-tester
        ports:
        - containerPort: 9999
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 120Mi
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
