---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8s-scheduler-tester
  name: k8s-scheduler-tester
spec:
  clusterIP: None
  ports:
  - name: http-9999
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    name: k8s-scheduler-tester
  type: ClusterIP
